# Generated by Django 5.0.6 on 2024-05-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='config',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='config',
            name='enabled',
        ),
    ]
